import type { DecisionDef } from "../schema/decisions.js";
import type { ModelDef } from "../schema/model.js";
import type { PolicyDef } from "../schema/policy.js";

import { getActions, getTransitions } from "./utils.js";

export type FeatureConstruct = DecisionDef | ModelDef | PolicyDef;

export type FeatureEntry = {
  /** Grouping label — the construct's `area`, or a folder-derived fallback. */
  area: string;
  def: FeatureConstruct;
};

/**
 * Aggregate Mermaid feature map across every construct, grouped by area.
 * Each construct is a node; its actions / transitions / rules are leaves.
 * Complements the per-construct diagrams produced by `generate`.
 */
export const generateFeatureMap = (
  entries: FeatureEntry[],
  options: { title?: string } = {},
): string => {
  const title = options.title ?? "Feature map";
  const order: string[] = [];
  const byArea = new Map<string, FeatureConstruct[]>();

  for (const { area, def } of entries) {
    let bucket = byArea.get(area);

    if (!bucket) {
      bucket = [];
      byArea.set(area, bucket);
      order.push(area);
    }

    bucket.push(def);
  }

  const lines: string[] = ["graph LR", `  ROOT(("${escape(title)}"))`, ""];
  const areaIds: string[] = [];
  const kindIds: Record<string, string[]> = {
    decision: [],
    model: [],
    policy: [],
  };
  const leafIds: string[] = [];

  let counter = 0;
  const nextId = (): string => `n${String(counter++)}`;

  for (const area of order) {
    const areaId = nextId();

    areaIds.push(areaId);
    lines.push(`  ROOT --> ${areaId}["${escape(area)}"]`);

    for (const def of byArea.get(area) ?? []) {
      const nodeId = nextId();

      kindIds[def.kind]?.push(nodeId);
      lines.push(
        `  ${areaId} --> ${nodeId}["${escape(def.name)} · ${kindWord(def.kind)}"]`,
      );

      for (const leaf of leavesOf(def)) {
        const leafId = nextId();

        leafIds.push(leafId);
        lines.push(`  ${nodeId} --> ${leafId}["${escape(leaf)}"]`);
      }
    }

    lines.push("");
  }

  lines.push(
    "  classDef root fill:#1a0dab,stroke:#0b0a6b,color:#ffffff,font-weight:bold;",
    "  classDef area fill:#e8f0fe,stroke:#4285f4,stroke-width:2px,color:#1a2024,font-weight:bold;",
    "  classDef model fill:#fef7e0,stroke:#f9ab00,stroke-width:2px,color:#1a2024;",
    "  classDef decision fill:#e6f4ea,stroke:#34a853,stroke-width:2px,color:#1a2024;",
    "  classDef policy fill:#fce8e6,stroke:#ea4335,stroke-width:2px,color:#1a2024;",
    "  classDef leaf fill:#f5f5f5,stroke:#9aa0a6,color:#1a2024;",
    "  class ROOT root;",
  );

  assignClass(lines, areaIds, "area");
  assignClass(lines, kindIds["model"] ?? [], "model");
  assignClass(lines, kindIds["decision"] ?? [], "decision");
  assignClass(lines, kindIds["policy"] ?? [], "policy");
  assignClass(lines, leafIds, "leaf");

  const diagram = lines.join("\n");

  return `# ${title}

<!-- Generated by \`dopespec map\` — grouped by area, one node per construct. -->

\`\`\`mermaid
${diagram}
\`\`\`
`;
};

function assignClass(lines: string[], ids: string[], cls: string): void {
  if (ids.length) lines.push(`  class ${ids.join(",")} ${cls};`);
}

const escape = (s: string): string => s.replace(/"/g, "'");

function kindWord(kind: string): string {
  return kind === "decision" ? "decisions" : kind;
}

function leavesOf(def: FeatureConstruct): string[] {
  if (def.kind === "model") {
    const actions = getActions(def).map(([key]) => key);

    if (actions.length) return actions;

    return getTransitions(def).map(([key]) => key);
  }

  if (def.kind === "decision") {
    return def.rules.map((rule) => {
      const r = rule as {
        then: Record<string, unknown>;
        when: Record<string, unknown>;
      };

      return `${pairs(r.when) || "*"} → ${pairs(r.then)}`;
    });
  }

  const effects = [...new Set(def.rules.map((rule) => rule.effect))].join("/");

  return [`${effects}: ${def.on.model.name}.${def.on.action}`];
}

function pairs(obj: Record<string, unknown>): string {
  return Object.entries(obj)
    .map(([key, value]) => `${key}=${String(value)}`)
    .join(", ");
}
